# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Solutis_Teste' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'JMMaskTextField-Swift'
  pod 'KeychainAccess'
  pod 'CPF-CNPJ-Validator'
  pod 'KeychainSwift'

end
